apiVersion: apps/v1
kind: Deployment
metadata:
  name: clusterapi-manager-controllers
  namespace: {{ .TargetNamespace }}
  labels:
    api: clusterapi
    k8s-app: controller
    tectonic-operators.coreos.com/managed-by: machine-api-operator
spec:
  securityContext:
    runAsNonRoot: true
    runAsUser: 65534
  selector:
    matchLabels:
      api: clusterapi
      k8s-app: controller
  replicas: 1
  template:
    metadata:
      labels:
        api: clusterapi
        k8s-app: controller
    spec:
      nodeSelector:
        node-role.kubernetes.io/master: ""
      tolerations:
      - effect: NoSchedule
        key: node-role.kubernetes.io/master
      - key: CriticalAddonsOnly
        operator: Exists
      - effect: NoExecute
        key: node.alpha.kubernetes.io/notReady
        operator: Exists
      - effect: NoExecute
        key: node.alpha.kubernetes.io/unreachable
        operator: Exists
      containers:
      - name: controller-manager
      {{- if eq .Provider "aws" }}
        image: {{ .Images.ClusterAPIControllerManagerAWS }}
      {{end}}
      {{- if eq .Provider "openstack" }}
        image: {{ .Images.ClusterAPIControllerManagerOpenStack }}
      {{end}}
      {{- if eq .Provider "libvirt" }}
        image: {{ .Images.ClusterAPIControllerManagerLibvirt }}
      {{- end}}
        command:
        - "./manager"
        resources:
          requests:
            cpu: 100m
            memory: 20Mi
          limits:
            cpu: 100m
            memory: 30Mi
      {{- if eq .Provider "aws" }}
      - name: aws-machine-controller
        image: {{ .Images.ClusterAPIControllerAWS }}
      {{end}}
      {{- if eq .Provider "openstack" }}
      - name: openstack-machine-controller
        image: {{ .Images.ClusterAPIControllerOpenStack }}
      {{end}}
      {{- if eq .Provider "libvirt" }}
      - name: libvirt-machine-controller
        image: {{ .Images.ClusterAPIControllerLibvirt }} 
      {{- end}}
        env:
          - name: NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
        command:
          - /machine-controller-manager
        args:
          - --log-level=debug
        resources:
          requests:
            cpu: 100m
            memory: 20Mi
          limits:
            cpu: 100m
            memory: 30Mi
