apiVersion: apiregistration.k8s.io/v1beta1
kind: APIService
metadata:
  name: v1alpha1.cluster.k8s.io
  labels:
    api: clusterapi
    apiserver: "true"
spec:
  version: v1alpha1
  group: cluster.k8s.io
  groupPriorityMinimum: 2000
  versionPriority: 200
  service:
    name: clusterapi
    namespace: {{ .TargetNamespace }}
  versionPriority: 10
  caBundle: {{ .EncodedAPIServiceCA }}
