apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: clusterapi
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: extension-apiserver-authentication-reader
subjects:
- kind: ServiceAccount
  name: default
  namespace: default
# TODO: create specifics service accounts
