apiVersion: cluster.k8s.io/v1alpha1
kind: MachineSet
metadata:
  name: worker
  namespace: test
  labels:
    machineapioperator.openshift.io/cluster: test
spec:
  replicas: 3
  selector:
    matchLabels:
      machineapioperator.openshift.io/machineset: worker
      machineapioperator.openshift.io/cluster: test
  template:
    metadata:
      labels:
        machineapioperator.openshift.io/machineset: worker
        machineapioperator.openshift.io/cluster: test
    spec:
      providerConfig:
        value:
          apiVersion: awsproviderconfig/v1alpha1
          kind: AWSMachineProviderConfig
          clusterId: {{.VpcName}}
          clusterHardware:
            aws:
              keyPairName: {{.SshKey}}
              region: {{.Region}}
          hardware:
            aws:
              instanceType: m4.large
          infra: false
          vmImage:
            awsImage: {{.Image}}
      versions:
        kubelet: 0.0.0
        controlPlane: 0.0.0
      roles:
      - Master

