apiVersion: v1
kind: ConfigMap
metadata:
  annotations:
    release.openshift.io/create-only: "true"
  labels:
    config.openshift.io/inject-trusted-cabundle: "true"
  name: machine-api-operator-trusted-ca
  namespace: openshift-machine-api
