apiVersion: v1
kind: ConfigMap
metadata:
  name: machine-api-operator-images
  namespace: openshift-cluster-api
data:
  images.json: '{"clusterAPIControllerAWS": "docker.io/openshift/origin-aws-machine-controllers:v4.0.0", "clusterAPIControllerOpenStack": "docker.io/openshift/origin-openstack-machine-controllers:v4.0.0", "clusterAPIControllerLibvirt": "docker.io/openshift/origin-libvirt-machine-controllers:v4.0.0"}'
